const DEFAULT_PRODUCTS=[
 {id:1,nameAr:'هودي أساسي أسود',nameEn:'Essential Black Hoodie',category:'hoodies',price:1450,descriptionAr:'هودي قطني مريح بتصميم بسيط يناسب الاستخدام اليومي.',descriptionEn:'Comfortable cotton hoodie with a clean everyday design.',materialAr:'قطن فاخر',materialEn:'Premium cotton',colors:[{ar:'أسود',en:'Black',code:'#111111'},{ar:'بيج',en:'Beige',code:'#d8c9b4'},{ar:'رمادي',en:'Gray',code:'#929292'}],sizes:['S','M','L','XL','XXL'],image:'assets/hoodie-black.png',visible:true},
 {id:2,nameAr:'تيشيرت أوفر سايز',nameEn:'Oversized T-Shirt',category:'tshirts',price:950,descriptionAr:'تيشيرت بقصة عصرية مريحة وخامة ناعمة.',descriptionEn:'A relaxed modern cut in soft fabric.',materialAr:'قطن ناعم',materialEn:'Soft cotton',colors:[{ar:'بيج',en:'Beige',code:'#ded1bf'},{ar:'أبيض',en:'White',code:'#f3f1ed'},{ar:'أسود',en:'Black',code:'#111111'}],sizes:['S','M','L','XL','XXL'],image:'assets/tee-beige.png',visible:true},
 {id:3,nameAr:'بنطلون كارجو',nameEn:'Cargo Pants',category:'pants',price:1750,descriptionAr:'بنطلون واسع بجيوب عملية وقصة مريحة.',descriptionEn:'Relaxed cargo pants with practical pockets.',materialAr:'قطن ثقيل',materialEn:'Heavy cotton',colors:[{ar:'أسود',en:'Black',code:'#151515'},{ar:'زيتي',en:'Olive',code:'#77745d'}],sizes:['S','M','L','XL'],image:'assets/cargo-black.png',visible:true},
 {id:4,nameAr:'جاكيت يومي',nameEn:'Everyday Jacket',category:'jackets',price:2100,descriptionAr:'جاكيت خفيف مناسب للخروجات اليومية.',descriptionEn:'Lightweight jacket for everyday outings.',materialAr:'قطن وبوليستر',materialEn:'Cotton blend',colors:[{ar:'أسود',en:'Black',code:'#202020'},{ar:'رمادي',en:'Gray',code:'#777777'}],sizes:['M','L','XL','XXL'],image:'assets/jacket-black.png',visible:true},
 {id:5,nameAr:'تيشيرت كلاسيك',nameEn:'Classic T-Shirt',category:'tshirts',price:790,descriptionAr:'قطعة أساسية خفيفة وسهلة التنسيق.',descriptionEn:'A light essential that is easy to style.',materialAr:'قطن',materialEn:'Cotton',colors:[{ar:'أوف وايت',en:'Off-white',code:'#e8e3da'},{ar:'أسود',en:'Black',code:'#111111'}],sizes:['S','M','L','XL'],image:'assets/tee-classic.png',visible:true},
 {id:6,nameAr:'هودي أوف وايت',nameEn:'Off-White Hoodie',category:'hoodies',price:1550,descriptionAr:'هودي أوف وايت بطابع بسيط ومميز.',descriptionEn:'Minimal off-white hoodie with a distinctive look.',materialAr:'قطن فاخر',materialEn:'Premium cotton',colors:[{ar:'أوف وايت',en:'Off-white',code:'#e5dbcc'},{ar:'بيج',en:'Beige',code:'#cdbda7'}],sizes:['S','M','L','XL','XXL'],image:'assets/hoodie-offwhite.png',visible:true}
];
const TEXT={ar:{heroTitle:'أناقة أبسط<br>بحضور أقوى',heroText:'قطع مختارة بعناية، جاهزة للتوصيل داخل مصر.',shopNow:'تسوّق الآن',collection:'مجموعتنا',allProducts:'كل المنتجات',search:'ابحث عن منتج...',installTitle:'ثبّت RAYAN على هاتفك',installText:'تجربة أسرع وتعمل حتى عند ضعف الإنترنت.',install:'تثبيت التطبيق',home:'الرئيسية',products:'المنتجات',contact:'تواصل',admin:'الإدارة',view:'عرض',noProducts:'لا توجد منتجات مطابقة.',specifications:'المواصفات',material:'الخامة',availability:'التوفر',availableEgypt:'متوفر داخل مصر',chooseColor:'اختر اللون',chooseSize:'اختر المقاس',quantity:'الكمية',orderWhatsApp:'اطلب الآن عبر واتساب',selectOptions:'اختر اللون والمقاس أولًا.',adminLogin:'دخول الإدارة',login:'دخول',wrongPassword:'كلمة السر غير صحيحة.',adminPanel:'لوحة إدارة RAYAN',welcomeAdmin:'مرحبًا، مدير المتجر',totalProducts:'إجمالي المنتجات',visibleProducts:'المنتجات الظاهرة',whatsappNumber:'رقم واتساب بصيغة دولية',save:'حفظ',addProduct:'إضافة منتج',exportData:'تصدير نسخة البيانات',importData:'استيراد البيانات',saved:'تم الحفظ بنجاح.',deleted:'تم حذف المنتج.',added:'تمت إضافة المنتج.',updated:'تم تعديل المنتج.',invalidFile:'ملف البيانات غير صالح.',installIos:'على iPhone: مشاركة ← إضافة إلى الشاشة الرئيسية',whatsappMissing:'أدخل رقم واتساب من الإدارة أولًا.'},en:{heroTitle:'Simpler style.<br>Stronger presence.',heroText:'Curated pieces, ready for delivery across Egypt.',shopNow:'Shop now',collection:'Our collection',allProducts:'All products',search:'Search products...',installTitle:'Install RAYAN',installText:'A faster experience that also works offline.',install:'Install app',home:'Home',products:'Products',contact:'Contact',admin:'Admin',view:'View',noProducts:'No matching products.',specifications:'Specifications',material:'Material',availability:'Availability',availableEgypt:'Available in Egypt',chooseColor:'Choose color',chooseSize:'Choose size',quantity:'Quantity',orderWhatsApp:'Order now on WhatsApp',selectOptions:'Choose a color and size first.',adminLogin:'Admin login',login:'Login',wrongPassword:'Incorrect password.',adminPanel:'RAYAN Admin',welcomeAdmin:'Welcome, store manager',totalProducts:'Total products',visibleProducts:'Visible products',whatsappNumber:'WhatsApp number with country code',save:'Save',addProduct:'Add product',exportData:'Export data backup',importData:'Import data',saved:'Saved successfully.',deleted:'Product deleted.',added:'Product added.',updated:'Product updated.',invalidFile:'Invalid data file.',installIos:'On iPhone: Share → Add to Home Screen',whatsappMissing:'Set the WhatsApp number in Admin first.'}};
const CATEGORY={all:{ar:'الكل',en:'All'},hoodies:{ar:'هوديز',en:'Hoodies'},tshirts:{ar:'تيشيرتات',en:'T-Shirts'},pants:{ar:'بناطيل',en:'Pants'},jackets:{ar:'جاكيتات',en:'Jackets'}};
const STORAGE={products:'rayan_products_v3',settings:'rayan_settings_v3',language:'rayan_language_v3'};
let products=loadProducts(),settings=loadSettings(),language=localStorage.getItem(STORAGE.language)||'ar',activeCategory='all',selectedProduct=null,selectedColor=null,selectedSize=null,quantity=1,deferredInstallPrompt=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function cloneDefaults(){return JSON.parse(JSON.stringify(DEFAULT_PRODUCTS))}
function loadProducts(){try{const value=JSON.parse(localStorage.getItem(STORAGE.products));return Array.isArray(value)&&value.length?value:cloneDefaults()}catch{return cloneDefaults()}}
function loadSettings(){try{return {...{whatsapp:'201000000000'},...JSON.parse(localStorage.getItem(STORAGE.settings)||'{}')}}catch{return{whatsapp:'201000000000'}}}
function saveProducts(){localStorage.setItem(STORAGE.products,JSON.stringify(products))}
function saveSettingsData(){localStorage.setItem(STORAGE.settings,JSON.stringify(settings))}
function t(key){return TEXT[language][key]||key}
function localField(item,ar,en){return language==='ar'?item[ar]:item[en]}
function money(value){return new Intl.NumberFormat(language==='ar'?'ar-EG':'en-US').format(value)+(language==='ar'?' ج.م':' EGP')}
function showToast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>el.classList.remove('show'),1900)}
function openLayer(el){el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeLayer(el){el.classList.remove('open');el.setAttribute('aria-hidden','true');if(!$$('.modal.open,.side-menu.open,.admin-screen.open').length)document.body.style.overflow=''}
function applyLanguage(){document.documentElement.lang=language;document.documentElement.dir=language==='ar'?'rtl':'ltr';$('#languageButton').textContent=language==='ar'?'EN':'عربي';$$('[data-i18n]').forEach(el=>{const value=t(el.dataset.i18n);if(value.includes('<br>'))el.innerHTML=value;else el.textContent=value});$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));renderCategories();renderProducts();if(selectedProduct)renderProductDetail();renderAdmin();localStorage.setItem(STORAGE.language,language)}
function renderCategories(){const keys=['all','hoodies','tshirts','pants','jackets'];$('#categoryFilters').innerHTML=keys.map(key=>`<button class="category-button ${activeCategory===key?'active':''}" data-category="${key}">${CATEGORY[key][language]}</button>`).join('');$$('.category-button').forEach(button=>button.onclick=()=>{activeCategory=button.dataset.category;renderCategories();renderProducts()})}
function filteredProducts(){const query=$('#searchInput').value.trim().toLocaleLowerCase(language==='ar'?'ar':'en');return products.filter(p=>p.visible&&(activeCategory==='all'||p.category===activeCategory)&&`${p.nameAr} ${p.nameEn}`.toLocaleLowerCase().includes(query))}
function renderProducts(){const list=filteredProducts();$('#productsGrid').innerHTML=list.length?list.map(p=>`<button class="product-card" data-id="${p.id}"><div class="product-image"><img src="${p.image}" alt="${escapeHtml(localField(p,'nameAr','nameEn'))}" loading="lazy"></div><div class="product-info"><h3>${escapeHtml(localField(p,'nameAr','nameEn'))}</h3><p>${CATEGORY[p.category]?.[language]||''}</p><div class="product-footer"><strong>${money(p.price)}</strong><span class="view-chip">${t('view')}</span></div></div></button>`).join(''):`<p class="empty-state">${t('noProducts')}</p>`;$$('.product-card').forEach(card=>card.onclick=()=>openProduct(Number(card.dataset.id)))}
function openProduct(id){selectedProduct=products.find(p=>p.id===id);if(!selectedProduct)return;selectedColor=null;selectedSize=null;quantity=1;renderProductDetail();openLayer($('#productModal'))}
function renderProductDetail(){const p=selectedProduct;if(!p)return;$('#detailImage').src=p.image;$('#detailImage').alt=localField(p,'nameAr','nameEn');$('#detailCategory').textContent=CATEGORY[p.category]?.[language]||'';$('#detailName').textContent=localField(p,'nameAr','nameEn');$('#detailPrice').textContent=money(p.price);$('#detailDescription').textContent=localField(p,'descriptionAr','descriptionEn');$('#detailMaterial').textContent=localField(p,'materialAr','materialEn');$('#quantityValue').textContent=quantity;$('#selectionWarning').textContent='';$('#colorOptions').innerHTML=p.colors.map((c,i)=>`<button class="color-choice ${selectedColor===i?'selected':''}" data-color="${i}"><i style="background:${safeColor(c.code)}"></i><span>${escapeHtml(language==='ar'?c.ar:c.en)}</span></button>`).join('');$('#sizeOptions').innerHTML=p.sizes.map(size=>`<button class="size-choice ${selectedSize===size?'selected':''}" data-size="${escapeHtml(size)}">${escapeHtml(size)}</button>`).join('');$$('.color-choice').forEach(button=>button.onclick=()=>{selectedColor=Number(button.dataset.color);renderProductDetail()});$$('.size-choice').forEach(button=>button.onclick=()=>{selectedSize=button.dataset.size;renderProductDetail()})}
function whatsappUrl(message=''){const number=String(settings.whatsapp||'').replace(/\D/g,'');return number?`https://wa.me/${number}${message?`?text=${encodeURIComponent(message)}`:''}`:''}
function placeWhatsAppOrder(){if(selectedColor===null||!selectedSize){$('#selectionWarning').textContent=t('selectOptions');return}const url=whatsappUrl();if(!url){$('#selectionWarning').textContent=t('whatsappMissing');return}const p=selectedProduct,c=p.colors[selectedColor];const message=language==='ar'?`مرحبًا، أريد طلب:\nالموديل: ${p.nameAr}\nاللون: ${c.ar}\nالمقاس: ${selectedSize}\nالكمية: ${quantity}\nالسعر: ${money(p.price*quantity)}`:`Hello, I would like to order:\nProduct: ${p.nameEn}\nColor: ${c.en}\nSize: ${selectedSize}\nQuantity: ${quantity}\nPrice: ${money(p.price*quantity)}`;window.open(whatsappUrl(message),'_blank','noopener')}
function openAdminLogin(){closeLayer($('#sideMenu'));$('#adminPassword').value='';$('#loginError').textContent='';openLayer($('#adminLoginModal'));setTimeout(()=>$('#adminPassword').focus(),100)}
function renderAdmin(){if(!$('#adminScreen').classList.contains('open'))return;$('#totalProductsCount').textContent=products.length;$('#visibleProductsCount').textContent=products.filter(p=>p.visible).length;$('#whatsappNumber').value=settings.whatsapp;$('#adminProductsList').innerHTML=products.map(p=>`<article class="admin-product"><img src="${p.image}" alt=""><div><h3>${escapeHtml(localField(p,'nameAr','nameEn'))}</h3><small>${money(p.price)} • ${p.visible?'●':'○'}</small></div><div class="admin-actions"><button class="edit-product" data-id="${p.id}" aria-label="Edit">✎</button><button class="toggle-product" data-id="${p.id}" aria-label="Show or hide">◉</button><button class="delete-product" data-id="${p.id}" aria-label="Delete">⌫</button></div></article>`).join('');$$('.edit-product').forEach(b=>b.onclick=()=>openProductForm(Number(b.dataset.id)));$$('.toggle-product').forEach(b=>b.onclick=()=>{const p=products.find(x=>x.id===Number(b.dataset.id));p.visible=!p.visible;saveProducts();renderAdmin();renderProducts()});$$('.delete-product').forEach(b=>b.onclick=()=>{if(confirm(language==='ar'?'حذف هذا المنتج؟':'Delete this product?')){products=products.filter(x=>x.id!==Number(b.dataset.id));saveProducts();renderAdmin();renderProducts();showToast(t('deleted'))}})}
function openProductForm(id=null){$('#productForm').reset();$('#productFormError').textContent='';$('#editProductId').value=id||'';const p=id?products.find(x=>x.id===id):null;$('#productFormTitle').textContent=p?(language==='ar'?'تعديل المنتج':'Edit product'):(language==='ar'?'إضافة منتج':'Add product');if(p){$('#productNameAr').value=p.nameAr;$('#productNameEn').value=p.nameEn;$('#productCategory').value=p.category;$('#productPrice').value=p.price;$('#productDescriptionAr').value=p.descriptionAr;$('#productDescriptionEn').value=p.descriptionEn;$('#productMaterialAr').value=p.materialAr;$('#productMaterialEn').value=p.materialEn;$('#productColors').value=p.colors.map(c=>`${c.ar}/${c.en}|${c.code}`).join(', ');$('#productSizes').value=p.sizes.join(',');$('#productVisible').checked=p.visible}openLayer($('#productFormModal'))}
function parseColors(value){return value.split(',').map(item=>{const [names,code]=item.trim().split('|');const [ar,en]=String(names||'').split('/');return{ar:(ar||'لون').trim(),en:(en||ar||'Color').trim(),code:safeColor((code||'#111111').trim())}}).filter(c=>c.ar)}
async function imageFileToDataUrl(file){if(!file)return'';return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{const max=1000,scale=Math.min(1,max/Math.max(img.width,img.height)),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.84))};img.src=reader.result};reader.readAsDataURL(file)})}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]))}
function safeColor(value){return /^#[0-9a-f]{3,8}$/i.test(value)?value:'#111111'}
function wireEvents(){$('#languageButton').onclick=()=>{language=language==='ar'?'en':'ar';applyLanguage()};$('#searchInput').oninput=renderProducts;$('#shopNowButton').onclick=()=>$('#productsSection').scrollIntoView({behavior:'smooth'});$('#homeButton').onclick=$('#navHome').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('#navProducts').onclick=$('#sideProducts').onclick=()=>{closeLayer($('#sideMenu'));$('#productsSection').scrollIntoView({behavior:'smooth'})};$('#menuButton').onclick=()=>openLayer($('#sideMenu'));$('#closeMenu').onclick=()=>closeLayer($('#sideMenu'));$('#sideMenu').onclick=e=>{if(e.target===$('#sideMenu'))closeLayer($('#sideMenu'))};$('#sideHome').onclick=()=>{closeLayer($('#sideMenu'));window.scrollTo({top:0,behavior:'smooth'})};$('#navAdmin').onclick=$('#sideAdmin').onclick=openAdminLogin;$('#closeProduct').onclick=()=>closeLayer($('#productModal'));$('#productModal').onclick=e=>{if(e.target===$('#productModal'))closeLayer($('#productModal'))};$('#favoriteButton').onclick=e=>{e.currentTarget.textContent=e.currentTarget.textContent==='♡'?'♥':'♡'};$('#minusQuantity').onclick=()=>{quantity=Math.max(1,quantity-1);$('#quantityValue').textContent=quantity};$('#plusQuantity').onclick=()=>{quantity=Math.min(20,quantity+1);$('#quantityValue').textContent=quantity};$('#whatsappOrder').onclick=placeWhatsAppOrder;$('#navWhatsApp').onclick=()=>{const url=whatsappUrl();url?window.open(url,'_blank','noopener'):showToast(t('whatsappMissing'))};$('#adminLoginForm').onsubmit=e=>{e.preventDefault();if($('#adminPassword').value==='6666'){closeLayer($('#adminLoginModal'));openLayer($('#adminScreen'));renderAdmin()}else $('#loginError').textContent=t('wrongPassword')};$('#closeAdminLogin').onclick=()=>closeLayer($('#adminLoginModal'));$('#closeAdmin').onclick=()=>closeLayer($('#adminScreen'));$('#saveSettings').onclick=()=>{const value=$('#whatsappNumber').value.replace(/\D/g,'');if(value.length<10){showToast(language==='ar'?'أدخل رقمًا صحيحًا':'Enter a valid number');return}settings.whatsapp=value;saveSettingsData();showToast(t('saved'))};$('#addProductButton').onclick=()=>openProductForm();$('#closeProductForm').onclick=()=>closeLayer($('#productFormModal'));$('#productForm').onsubmit=saveProductFromForm;$('#exportData').onclick=exportData;$('#importData').onchange=importData;$('#sideInstall').onclick=$('#installButton').onclick=installApp;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBanner').classList.remove('hidden')})}
async function saveProductFromForm(e){e.preventDefault();try{const id=Number($('#editProductId').value)||Date.now(),existing=products.find(p=>p.id===id),file=$('#productImage').files[0],newImage=await imageFileToDataUrl(file),colors=parseColors($('#productColors').value),sizes=$('#productSizes').value.split(',').map(s=>s.trim().toUpperCase()).filter(Boolean);if(!colors.length||!sizes.length)throw new Error('options');const item={id,nameAr:$('#productNameAr').value.trim(),nameEn:$('#productNameEn').value.trim(),category:$('#productCategory').value,price:Number($('#productPrice').value),descriptionAr:$('#productDescriptionAr').value.trim(),descriptionEn:$('#productDescriptionEn').value.trim(),materialAr:$('#productMaterialAr').value.trim(),materialEn:$('#productMaterialEn').value.trim(),colors,sizes,image:newImage||(existing?.image)||'assets/tee-classic.png',visible:$('#productVisible').checked};if(existing)products=products.map(p=>p.id===id?item:p);else products.unshift(item);saveProducts();closeLayer($('#productFormModal'));renderProducts();renderAdmin();showToast(t(existing?'updated':'added'))}catch{$('#productFormError').textContent=language==='ar'?'راجع البيانات والألوان والمقاسات.':'Check the fields, colors, and sizes.'}}
function exportData(){const blob=new Blob([JSON.stringify({version:3,products,settings},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='rayan-data-backup.json';a.click();URL.revokeObjectURL(url)}
function importData(e){const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!Array.isArray(data.products))throw new Error('invalid');products=data.products;settings={...settings,...data.settings};saveProducts();saveSettingsData();renderProducts();renderAdmin();showToast(t('saved'))}catch{showToast(t('invalidFile'))}e.target.value=''};reader.readAsText(file)}
async function installApp(){closeLayer($('#sideMenu'));if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null}else showToast(t('installIos'))}
wireEvents();applyLanguage();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
